### ISSUE TITLE
Discussion: Avoiding downtime due to seal on restart

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry-community/vault-boshrelease#16]
Hi all,

New to Vault, still trying to wrap my head around it. As I understand it, Vault automatically seals itself on restart as it doesn't persist the unseal keys. While more secure, this seems like a rough match for the BOSH deployment process as bumping a stemcell results in Vault downtime until a human or multiple humans run `vault unseal`.

Any thoughts on adding automatic unsealing to this release to allow a more usual BOSH workflow or would that be sacrificing a valuable security feature? Related thread on Vault GH here: https://github.com/hashicorp/vault/issues/72.

**Comment by jhunt** [comment]
Personally, I feel like this undermines the general security of the Vault, by making the seal feature essentially useless.

If you want to, you could always script the bosh deployment with the unseal keys, _outside_ of the purview of the BOSH release (i.e. in concourse, or a BASH script, or something similar)

**Comment by ljfranklin** [comment]
@jhunt Seems like that's the general consensus, trade a bit of UX for added security. The Vault Enterprise release seems to support automatic unseal but requires a Hardware Security Module: https://atlas.hashicorp.com/help/vault/hsm. Turtles all the way down. Closing out, but still interested if others have thoughts on this.

**Comment by jhunt** [comment]
Yeah, we've struggled with the "secret zero" problem for a while now, and no matter which way we look at it, we end up coming back to "you have to have a human do this part, or the security of the whole system breaks down"

😞
