### ISSUE TITLE
Recommendation for health checks / discovering unsealed vaults

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry-community/vault-boshrelease#18]
From the sample templates included here, I'm not sure how / whether you recommend setting up service discovery and health checks so that clients don't hit sealed vault instances. For example, the vault consul backend adds a `vault` service with `active` and `standby` tags, so that clients using consul dns can access `active.vault.service.consul`. Or clients can hit vault via a load balancer that uses the vault health check endpoint, as in https://github.com/hashicorp/vault/blob/master/terraform/aws/main.tf#L76-L107. This might be out of scope for this release, but I think adding recommendations for health checks of some kind would be useful. WDYT?

**Comment by jhunt** [comment]
Are you recommending adding additional health checks above and beyond what the Consul backend provides?  Or are you talking about registering with an external Consul instance?

**Comment by jmcarp** [comment]
Maybe I'm misunderstanding--what I'm trying to ask is how you make sure that clients only talk to unsealed vault instances. If clients look up vault instances via consul dns, then you're already done. Or if clients don't have access to consul, you might use an external load balancer with a health check.

**Comment by jhunt** [comment]
I don't think we _can_ make sure that clients only talk to unsealed Vaults, not without explicit Vault-aware support in the client binary / library.

**Comment by jhunt** [comment]
An example of Vault-aware client machinery is the forthcoming HA support in `safe`, once we finish reviewing and merge this PR: https://github.com/starkandwayne/safe/pull/45

**Comment by jmcarp** [comment]
Vault itself doesn't know how to prevent clients from accessing sealed instances, but it does include a health check endpoint that can be used by a load balancer to remove sealed instances from service--that's exactly what the example load balancer in the vault docs at https://github.com/hashicorp/vault/blob/master/terraform/aws/main.tf#L76-L107 is used for. And like I mentioned earlier, if clients use consul dns to find vault instances, the `vault.service.consul` name will resolve to all unsealed vault instances. My question is which of those approaches you use to prevent clients from talking to sealed instances, if any. It sounds like the answer is none of the above, but that you're going to solve the issue using your client instead.

In any case, I think it would be useful to include a note on this in the docs, even if only to say that you recommend using `safe`, which handles the issue, and that users of different clients will want to solve the problem of sealed instances on their own.

**Comment by simonkey007** [comment]
I bypassed this issue on AWS by setting a health check on HTTPS:8200/v1/sys/leader which returns 500 only on sealed instances so they are treated by ELB as out of service.

**Comment by jhunt** [comment]
We've done similar things with haproxy fronting Vault, but have run into minor issues during the post-update "everything-is-sealed" scenario.  How are you solving that in AWS, @simonkey007 ?

**Comment by simonkey007** [comment]
We have a script that every minute checks all the instances, one by one and unseal them if they are sealed.

**Comment by jhunt** [comment]
I wonder if it would be worthwhile to package that up as a post-start or post-deploy script (optional, controlled by `vault.auto_unseal: true` in the manifest) or not.

**Comment by alexanelli** [comment]
@jmcarp @simonkey007 just checking to see if you've looked any further into this; Thanks :)

**Comment by drnic** [comment]
@simonkey007 is your (cron?) script still the solution that works for you?

**Comment by simonkey007** [comment]
@drnic We removed the script from Concourse due to the security reasons. We didn't want to keep unseal keys in one place and we decided to leave the unsealing part as the manual job. Now we have a Concourse job that checks if any Vault instance is sealed and if yes, then it sends an email notification to key holders.

**Comment by jhunt** [comment]
Just an aside, if you use the safe-boshrelease (https://github.com/cloudfoundry-community/safe-boshrelease), then `safe seal` and `safe unseal` start working and do the magical needful.
