### ISSUE TITLE
vault unbind error question

### ISSUE THREAD

**Issue by marcus-sds** [cloudfoundry-community/vault-boshrelease#36]
Hi. We are using vault cluster with consul.
When we try to unbind the consul, it's failing with below messages. Can I know why and how can I debug?

2017/09/21 11:55:45 [unbind ea9e3158-eb34-4e72-9e52-6e8c7efaca1d / 8dde40c2-8dda-43fc-8def-3b2225017e1f] unbinding service
2017/09/21 11:55:45 [unbind ea9e3158-eb34-4e72-9e52-6e8c7efaca1d / 8dde40c2-8dda-43fc-8def-3b2225017e1f] using vault at https://SECRET
2017/09/21 11:55:45 [unbind ea9e3158-eb34-4e72-9e52-6e8c7efaca1d / 8dde40c2-8dda-43fc-8def-3b2225017e1f] retrieving access token
2017/09/21 11:55:45 [unbind ea9e3158-eb34-4e72-9e52-6e8c7efaca1d / 8dde40c2-8dda-43fc-8def-3b2225017e1f] revoking token '9SECRETb'
2017/09/21 11:55:45 [unbind ea9e3158-eb34-4e72-9e52-6e8c7efaca1d / 8dde40c2-8dda-43fc-8def-3b2225017e1f] error: vault returned a 200 OK

There is no error messages at vault and consul also.
CF api return message is 
    "error_details": {
      "description": "Service instance vault-svc: Service broker error: Received 200 OK from Vault",
      "error_code": "CF-ServiceBrokerBadResponse",
      "code": 10001,
      "http": {
        "uri": "https://SECRET/v2/service_instances/ea9e31588-eb34-4e72-9e52-6e8c7efaca1d/service_bindings/8dde40c2-8dda-43fc-8def-3b2225017e1f",
        "method": "DELETE",
        "status": 500
      }

* Broker's Revoke return message seems like this
{"request_id":"96acdd59-30d2-6f5e-8652-64ea70a0b5eb","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":["Using a token in the path is unsafe as the token can be logged in many places. Please use POST or PUT with the token passed in via the \"token\" parameter."],"auth":null}

**Comment by marcus-sds** [comment]
when I try through vault broker app,it's working. But only bosh release broker is not working.  It seems unbind 200 code return issue and release version broker sends token with path included. Can you check?

**Comment by jhunt** [comment]
My guess is that the vault-broker blob is out of date.  Looks like its from May 2016, so it doesn't have https://github.com/cloudfoundry-community/vault-broker/commit/2698650df3b379ccb0ac73bbd39435ba4534dc6a which should fix your problem.

Time to institute versioning on vault-broker and set up CI to watch for new releases of vault-broker and pull them into the BOSH release.  I'll try to get to that today or early next week.

**Comment by jhunt** [comment]
@marcus-sds I'm cutting an 0.8.0 release of vault-boshrelease; can you try that and see if this issue goes away?

**Comment by marcus-sds** [comment]
I've tested with 0.8.0 and it's working. Thank you.

**Comment by jhunt** [comment]
Awesome!  Glad to hear it.
