### ISSUE TITLE
Cut a new release please!

### ISSUE THREAD

**Issue by simonjohansson** [cloudfoundry-community/vault-boshrelease#52]
Could you cut a new release?
I would like to use the official release instead of my fork with google cloud support.. :)

**Comment by jhunt** [comment]
Hoping to get #51 merged in before then.

**Comment by jhunt** [comment]
#51 is merged.  Once I write up proper release notes, and add a section to the README on migration, we'll cut a new release.

**Comment by jhunt** [comment]
1.0.0 is out; so now you can use `vault.config` to your heart's content!
