### ISSUE TITLE
LDAP Auth Method

### ISSUE THREAD

**Issue by solera-concourse** [cloudfoundry-community/vault-boshrelease#53]
How can I enable and configure LDAP Auth Method to vault-boshrelease ?

**Comment by MattSurabian** [comment]
This is something that would happen "out of band" and not during the deploy process. After the Vault is initialized and unsealed you can enable the LDAP auth backend and write the configuration like it says in the documentation: https://www.vaultproject.io/docs/auth/ldap.html

A functional config will likely look something like this:
```  
vault write auth/ldap/config                        \
    url=ldaps://LDAP_SERVER:LDAP_PORT                 \
    discoverdn=true                                   \
    userattr=uid                                      \
    userdn=ou=accounts,dc=companyName,dc=com          \
    groupdn=ou=groups,dc=companyNamedc=com            \
    insecure_tls=false                                \
    starttls=true
```
