### ISSUE TITLE
cluster_address and redirect_address in README.me

### ISSUE THREAD

**Issue by ywei2017** [cloudfoundry-community/vault-boshrelease#55]
Reading the 1.0.0 release, and need some help to piece the config together.

The storage "consul" example shows "cluster_address", I think it should be "cluster_addr", based on the [documentation](https://www.vaultproject.io/docs/configuration/index.html).

Thanks
Yansheng

**Comment by ywei2017** [comment]
I tried more with the release, I think I know the proper config.
- "redirect_address" is not needed.
- At the top level should be (quote is required)
  api_addr = "https://vault_fqdn:8200"

So just need to update the doc.

Thanks
Yansheng

**Comment by MattSurabian** [comment]
Thanks for catching this @ywei2017

**Comment by ywei2017** [comment]
Hi, Matt,

I saw the P/R and spotted a few errors. I must have not made myself clear earlier. I commented on the P/R itself and hope it helps.

Thanks
Yansheng

**Comment by jhunt** [comment]
Fixed in #56
