### ISSUE TITLE
vault post-start failed due to SSL check error

### ISSUE THREAD

**Issue by ywei2017** [cloudfoundry-community/vault-boshrelease#59]
I am opening this as a separate issue from #58 . 

The reason release 1.0.0 gets the ssl error (but was fine 0.8.3) is due to the code `vault_addr=p("vault.address", "")` now always returns "", and therefore VAULT_SKIP_VERIFY will not be set.

While this can be considered as bug since it breaks behavior from 0.8.3, I would argue the original feature was a bad idea of ignoring SSL check. So it can be handled multiple ways.

- Update the readme requiring SAN IP be included in the cert (that works as I verified). This would be my recommendation.
- Or update the file to be backward compatible. This can be cheated by requiring the config to include a dumb property like "address: https" to fool the script and having VAULT_SKIP_VERIFY to be set. The parameter would have no other purpose as well. The more you think about this, the more you feel it is a bad idea. 

https://github.com/cloudfoundry-community/vault-boshrelease/blob/24eda8699183ab079c342e032cf20b7a112a1d1f/jobs/vault/templates/data/properties.sh.erb#L17

**Comment by jhunt** [comment]
Let's go ahead with the README update.  Care to submit a PR?

**Comment by ywei2017** [comment]
@jhunt The README is updated on P/R #60

**Comment by jhunt** [comment]
This should be fixed in 1.0.1: https://github.com/cloudfoundry-community/vault-boshrelease/releases/tag/v1.0.1
