### ISSUE TITLE
Vault HA configurations, how to use, and how it works?

### ISSUE THREAD

**Issue by Alexvianet** [cloudfoundry-community/vault-boshrelease#61]
i have 3 nodes with vault with s3 backend, with static ips:

vault/46ed57a5-e09d-4037-aaf3-783f4c291067        running        az2  101.35.96.73  
vault/6ef5fbf7-d4d7-438a-bdfd-b4d67453ab87        running        az1  101.35.96.71   (master node)
vault/c382f314-9af1-4204-bb9c-91bac745eac0        running        az3  101.35.96.72 

but the client has only one record:
export VAULT_ADDR=https://vault-dev.net:8200
vault-dev.net - 101.35.96.71  (master node)
How to configure HA correctly?

e.g:
if vault/6ef5fbf7-d4d7-438a-bdfd-b4d67453ab87        running        DC10P1  101.35.96.71  
will down how it will works ?

If the master node goes down, there is no automatic failover/load balancing. Because the DNS is pointing at a specific node.

**Comment by jhunt** [comment]
That is, unfortunately, just how Vault HA works.  If you're interested in a load-balancable Vault, where we've patched up some of these blindspots, take a look at the Safe BOSH release (https://github.com/cloudfoundry-community/safe-boshrelease) and the Safe CLI (https://github.com/starkandwayne/safe)
