### ISSUE TITLE
DynamoDB Unmarshal errors 

### ISSUE THREAD

**Issue by MattSurabian** [cloudfoundry-community/vault-boshrelease#69]
Just noting here in case others run into this nasty issue caused by a bug in the aws-sdk: https://github.com/hashicorp/vault/issues/4721

It's fixed in master right now but until 0.10.3 gets released it's probably best to downgrade back to the 1.0.0 bosh release.

**Comment by lrstanley** [comment]
I'm assuming this can be closed? Quite a few versions since this was fixed: https://github.com/hashicorp/vault/pull/4744

**Comment by MattSurabian** [comment]
Yea the binary in this release should have this, thanks!
