### ISSUE TITLE
Cut releases for Vault 0.11.1 and 0.11.2?

### ISSUE THREAD

**Issue by stuart-c-moore** [cloudfoundry-community/vault-boshrelease#70]
Hi,

Can you please cut some releases for vault 0.11.1 and vault 0.11.2?

Thanks,

**Comment by stuart-c-moore** [comment]
... and 0.11.3 which was released on October 8th.

**Comment by jhunt** [comment]
0.11.2 released in https://github.com/cloudfoundry-community/vault-boshrelease/releases/tag/v1.0.3

**Comment by thomasmitchell** [comment]
0.11.4 was released yesterday!
