### ISSUE TITLE
vault: 0.11.5 released

### ISSUE THREAD

**Issue by lrstanley** [cloudfoundry-community/vault-boshrelease#71]
https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#0115-november-12th-2018

Do we also want to push a 1.0.0 beta2 release version?

**Comment by lrstanley** [comment]
Hah, I see they haven't even pushed the binaries to the releases endpoint.

**Comment by lrstanley** [comment]
v1.0.0 has now been released as well..

https://releases.hashicorp.com/vault/1.0.0/

**Comment by jhunt** [comment]
1.1.0 of this BOSH release now has 1.0.0 of Vault!

https://github.com/cloudfoundry-community/vault-boshrelease/releases/tag/v1.1.0
