### ISSUE TITLE
vault v1.0.1

### ISSUE THREAD

**Issue by lrstanley** [cloudfoundry-community/vault-boshrelease#74]
Sorry to keep bugging 😄 

https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#101-december-14th-2018

**Comment by jhunt** [comment]
Done!  Should be in the next release.

**Comment by jhunt** [comment]
https://github.com/cloudfoundry-community/vault-boshrelease/releases/tag/v1.1.1
