### ISSUE TITLE
HA Backend properties is not present in erb file

### ISSUE THREAD

**Issue by chrisrana** [cloudfoundry-community/vault-boshrelease#8]
Hi I am trying to implement vault HA .I don't see ha_backend ,advertise_addr  properties in erb file.

 https://www.vaultproject.io/docs/config/#ha_backend

**Comment by jhunt** [comment]
They are definitely not there.  I will get those added!

**Comment by jhunt** [comment]
Out of curiosity, is there a reason you are unable to use the `backend` for HA?

Per the linked documentation:

> If not set, HA will be attempted on the backend given in the backend parameter.

I use consul as a backend and get HA that way.

**Comment by jhunt** [comment]
#10 introduced some changes to allow manually specifying the vault `advertise_addr` property, which is essential for proper HA operation.  @chrisrana can you give that a shot and let me know if it works for you?
